title: AyesC
email: ayesc@ayesc.ca
description: The Jekyll project for my personal website
repo: https://github.com/ayesc9000/AyesCNET
baseurl: ""
url: "https://ayesc.ca"
plugins:
  - jekyll-feed
include:
  - _pages
