title: AyesC
author: Liam "AyesC" Hogan
email: ayesc@ayesc.ca
repo: https://github.com/ayesc9000/AyesCNET
highlighter: rouge
baseurl: ""
url: "https://ayesc.ca"
plugins:
  - jekyll-feed
  - jekyll-toc
include:
  - _pages
exclude:
  - .jekyll-cache
  - .vscode
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md